language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 28.0.3
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew build connectedCheck