language: android
sudo: false
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 28.0.3
    - platform-tools
    - build-tools-28.0.3
    - android-28
before_install:
  - chmod +x gradlew
script:
   - ./gradlew build connectedCheck